In [4]:
# Numpy installed globally from Command prompt (pip install numpy)
import numpy as np

In [5]:
# 1D Arrays
arr = np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [9]:
print(arr.dtype)

int64


In [19]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [20]:
arr2

array([1, 2, 3, 4, 5])

In [21]:
Z=np.zeros(5)

In [22]:
Z

array([0., 0., 0., 0., 0.])

In [25]:
Z=np.ones(5)

In [26]:
Z

array([1., 1., 1., 1., 1.])

In [27]:
ar=np.arange(0,10,1)

In [28]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
## random rand function always takes values between 0 -1
ran=np.random.rand(5)

In [33]:
ran

array([0.28902786, 0.86660174, 0.8041475 , 0.94707095, 0.68180499])

In [35]:
ln = np.linspace(0,100,10)

In [38]:
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [40]:
# 2D Arrays
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [41]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
Z=np.zeros([5,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
o1 = np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
# Identity Matrix
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
r1 = np.random.rand(9,4,)
r1

array([[0.86259882, 0.14255893, 0.26148992, 0.47484895],
       [0.559261  , 0.41246748, 0.11670642, 0.46817437],
       [0.67162182, 0.63186792, 0.80476949, 0.49749719],
       [0.64640817, 0.96288882, 0.71992601, 0.28220841],
       [0.50147412, 0.09846256, 0.08725937, 0.19172285],
       [0.55185136, 0.68235692, 0.23359411, 0.51555804],
       [0.44930866, 0.23594099, 0.59300716, 0.53943105],
       [0.69466441, 0.52466951, 0.68663545, 0.27492923],
       [0.41067699, 0.38043301, 0.34430446, 0.96310708]])

In [55]:
arr

array([1, 2, 3, 4, 5])

In [56]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
print(arr.size)

5


In [58]:
print(ar2.size)

9


In [59]:
print(arr.shape)

(5,)


In [60]:
print(ar2.shape)

(3, 3)


In [62]:
# Operations in Array

ar3 = np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
ar3[2,2] = 10

In [64]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [65]:
ar3[1,2] =12
ar3[0,1] =15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [66]:
ar3 = np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [67]:
ar3 = np.sort(ar3,axis = 0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [69]:
ar3.sum(axis = 0)

array([12, 16, 37])

In [70]:
ar3.sum(axis = 1)

array([14, 21, 30])

In [71]:
ar4 = np.random.rand(99)
ar4

array([0.71871485, 0.62711115, 0.45897081, 0.64954073, 0.64603453,
       0.667304  , 0.12092559, 0.89338478, 0.48065929, 0.13703846,
       0.88696523, 0.50688314, 0.02006611, 0.89036935, 0.58909575,
       0.97814146, 0.58481965, 0.81860454, 0.20664859, 0.57702073,
       0.55035168, 0.99182597, 0.48072678, 0.06139237, 0.11698786,
       0.93770366, 0.36323751, 0.47301352, 0.40140045, 0.30343755,
       0.42850482, 0.72523844, 0.00938416, 0.53788167, 0.29518613,
       0.87289575, 0.23876473, 0.74919049, 0.18211429, 0.70088187,
       0.09414423, 0.43590693, 0.75563805, 0.88877486, 0.08697418,
       0.71155009, 0.40090315, 0.50958268, 0.86334294, 0.80691778,
       0.78487548, 0.173221  , 0.24144043, 0.77668544, 0.76171031,
       0.64915264, 0.72903337, 0.03537485, 0.35053626, 0.57181485,
       0.70610793, 0.71928516, 0.79157452, 0.52504261, 0.08388008,
       0.89269575, 0.38442711, 0.82336818, 0.72631562, 0.41318787,
       0.03273642, 0.82544138, 0.42319354, 0.73413723, 0.50998

In [72]:
x = np.random.rand(5,5)
x

array([[0.73085769, 0.35354173, 0.31456427, 0.80827829, 0.31986073],
       [0.11196894, 0.8489239 , 0.68655417, 0.35248689, 0.68483733],
       [0.37283031, 0.30572181, 0.42085865, 0.34050489, 0.84787888],
       [0.650692  , 0.96876814, 0.93115063, 0.88318074, 0.19399692],
       [0.14945869, 0.66671845, 0.23501851, 0.66858629, 0.3647633 ]])

In [73]:
x = np.random.rand(5,5,5)
x

array([[[0.77983618, 0.6923327 , 0.70218188, 0.74290845, 0.44801769],
        [0.72384958, 0.42691407, 0.51369955, 0.38145098, 0.93552898],
        [0.26459729, 0.98847121, 0.7760799 , 0.35066751, 0.30513289],
        [0.37786057, 0.7396947 , 0.85969624, 0.11663808, 0.06769371],
        [0.85044107, 0.64008038, 0.72541172, 0.2530406 , 0.45399987]],

       [[0.48590214, 0.31765201, 0.85504786, 0.66662672, 0.84535019],
        [0.42673347, 0.85243078, 0.64804014, 0.62204606, 0.56873757],
        [0.79558574, 0.4828915 , 0.48369795, 0.38247743, 0.00131165],
        [0.41095067, 0.25077509, 0.40516618, 0.01241106, 0.19977732],
        [0.4903406 , 0.87814822, 0.98025607, 0.45663041, 0.56734842]],

       [[0.27957014, 0.29426821, 0.13113171, 0.72591826, 0.30371237],
        [0.15057827, 0.88147697, 0.43687546, 0.93316919, 0.3956073 ],
        [0.62892202, 0.03569455, 0.83664161, 0.44278144, 0.86667622],
        [0.98801977, 0.85429711, 0.25662473, 0.3346138 , 0.57137132],
        [0.31638

In [77]:
print(arr.size)

5


In [82]:
print(ar2.size)

9


In [79]:
print(ar.shape)

(5,)


In [81]:
print(ar2.shape)

(3, 3)


In [83]:
arr3 = np.copy(ar2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr3[2,2] = 10
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [85]:
arr3[1,2] =12
arr3[2,1] = 15
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 15, 10]])

In [86]:
arr3 = np.sort(arr3)
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [87]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.append(ar, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [94]:
ar = np.append(ar,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 20, 20])

In [95]:
ar = np.delete(ar, 6, axis = 0)
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 20, 20, 20])

In [96]:
ar = np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 20, 20])

In [97]:
#Concatention
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [99]:
ar4 = np.concatenate((ar2, ar3),axis = 0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [100]:
ar5 = np.concatenate((ar2, ar3),axis = 1)
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [101]:
# Using Split function
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [102]:
ar6 = np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [103]:
# Scaler Expressions
# Addition
np.add(ar5,1)

array([[ 2,  3,  4,  2,  4, 11],
       [ 5,  6,  7,  5,  6, 13],
       [ 8,  9, 10,  8,  9, 16]])

In [104]:
# Subtraction
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  2,  9],
       [ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  7, 14]])

In [105]:
# Multiplication
np.multiply(ar5,1)

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [106]:
# Divide 
np.divide(ar5,1)

array([[ 1.,  2.,  3.,  1.,  3., 10.],
       [ 4.,  5.,  6.,  4.,  5., 12.],
       [ 7.,  8.,  9.,  7.,  8., 15.]])

In [116]:
# Vector Operations
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [108]:
# Addition
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  8, 16]])

In [115]:
# Subtraction
ar8 = np.subtract(ar6[0],ar6[1])
ar8

array([[-6, -6, -6],
       [ 3,  2, -4]])

In [110]:
# Multiplication
ar9 = np.multiply(ar6[0],ar6[1])
ar9

array([[ 7, 16, 27],
       [ 4, 15, 60]])

In [111]:
# Divide
ar10 = np.divide(ar6[0],ar6[1])
ar10

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.66666667, 0.6       ]])

In [112]:
np.ceil(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [113]:
np.floor(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [114]:
np.round(ar9)

array([[ 7, 16, 27],
       [ 4, 15, 60]])

# Statistics



In [117]:
np.mean(ar5)

np.float64(6.111111111111111)

In [118]:
np.mean(ar5,axis = 0)

array([ 4.        ,  5.        ,  6.        ,  4.        ,  5.33333333,
       12.33333333])

In [119]:
np.mean(ar5, axis = 1)

array([3.33333333, 6.        , 9.        ])

In [120]:
np.median(ar5, axis = 1)

array([2.5, 5. , 8. ])

In [121]:
np.min(ar5)

np.int64(1)

In [122]:
np.min(ar5, axis = 0)

array([ 1,  2,  3,  1,  3, 10])

In [123]:
np.max(ar5, axis = 0)

array([ 7,  8,  9,  7,  8, 15])

In [126]:
ar10 = np.array([2,5,3,8,0,4,1,6,9])
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [127]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [128]:
np.argmax(ar10)

np.int64(8)

In [129]:
np.argmin(ar10)

np.int64(4)

In [130]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8])

In [131]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [132]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [133]:
np.log(ar10)

C:\Users\gagan\AppData\Local\Temp\ipykernel_17496\168028880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])