In [1]:
import numpy as np
scores=np.array([[85,90,78],
                 [92,88,95],
                 [76,95,85],
                 [90,85,92],
                 [88,76,89]])
print(scores)

[[85 90 78]
 [92 88 95]
 [76 95 85]
 [90 85 92]
 [88 76 89]]


In [2]:
#mean score of each subject(across all student)
mean_scores=np.mean(scores,axis=1)
print(mean_scores)

[84.33333333 91.66666667 85.33333333 89.         84.33333333]


In [3]:
#median scores of each student(across all student)
median_scores=np.median(scores,axis=1)
print(median_scores)

[85. 92. 85. 90. 88.]


In [8]:
#extract the scores of the student of witth he highest total score(sum of all subjects)
total_scores=np.sum(scores,axis=1)
index_highest_total = np.argmax(total_scores)
highest_total_scores = scores[index_highest_total]

print("Total scores of each student:", total_scores)
print("Highest total scores:", highest_total_scores)


Total scores of each student: [253 275 256 267 253]
Highest total scores: [92 88 95]


In [7]:
#4 find the minnimum and maximum in scores in each subject
minimum_scores=np.min(scores,axis=0)
maximum_scores=np.max(scores,axis=0)
print("minimum scores in each subject:",minimum_scores)
print("maximum marks in each student:",maximum_scores)

minimum scores in each subject: [76 76 78]
maximum marks in each student: [92 95 95]


In [28]:
#reshape the array to have shape(3,5)where each row represents a subject and each column reepresent a student.

reshaped_scores=scores.reshape(3,5)
print(reshaped_scores)

[[85 90 78 92 88]
 [95 76 95 85 90]
 [85 92 88 76 89]]


In [22]:
#sort the scores of each subject in ascending order
sort_scores=np.sort(scores,axis=0)
print("sorted scores of each subject:\n",sort_scores)

sorted scores of each subject:
 [[76 76 78]
 [85 85 85]
 [88 88 89]
 [90 90 92]
 [92 95 95]]


In [25]:
#descending sort
descending_sort=np.sort(scores,axis=0)[::-1]
descending_sort


array([[92, 95, 95],
       [90, 90, 92],
       [88, 88, 89],
       [85, 85, 85],
       [76, 76, 78]])

***Akshit***