In [29]:
import numpy as np 
#bulinfunctions 1d
ran = np.random.rand(5)
print(ran)
print('\n')
ln = np.linspace(0,100,10)
print(ln)
Z=np.zeros(5)
print(" ")
print(Z)

[0.85983202 0.23287868 0.9774706  0.44921996 0.48002558]


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
 
[0. 0. 0. 0. 0.]


In [33]:
ln = np.linspace(0,100,10)
Z=np.zeros(5)

In [34]:
ln
Z

array([0., 0., 0., 0., 0.])

In [36]:
ran=np.linspace(0,100,10)

In [37]:
ran

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [39]:
o1=np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
I=np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
r1=np.random.rand(4,5)
r1

array([[0.68331671, 0.09430472, 0.51165624, 0.37210524, 0.69398222],
       [0.14530227, 0.0428564 , 0.29494779, 0.98223944, 0.35662673],
       [0.79224472, 0.71046051, 0.41972649, 0.64648528, 0.84330924],
       [0.29087077, 0.82920496, 0.7272441 , 0.48846422, 0.50712104]])

In [47]:
r1=np.random.rand(4,5,5)#3d array
r1

array([[[0.79121148, 0.01514292, 0.57610566, 0.98663694, 0.51238984],
        [0.33560869, 0.17652926, 0.92925571, 0.3813045 , 0.28415049],
        [0.52355112, 0.37786078, 0.81743861, 0.55545418, 0.00352938],
        [0.09876539, 0.48401356, 0.96858251, 0.49061453, 0.11088942],
        [0.94845177, 0.28443375, 0.27804719, 0.87281992, 0.0235504 ]],

       [[0.66102872, 0.80447304, 0.72210398, 0.07329313, 0.91923918],
        [0.0524821 , 0.02599978, 0.53673923, 0.84271546, 0.241465  ],
        [0.14135661, 0.7103564 , 0.63721574, 0.45835112, 0.36488413],
        [0.13687417, 0.94025206, 0.40470488, 0.70567007, 0.23278224],
        [0.41896265, 0.16217025, 0.40417913, 0.44317264, 0.33999019]],

       [[0.67853452, 0.67154307, 0.01163765, 0.92348423, 0.25232003],
        [0.0293337 , 0.27448408, 0.14569942, 0.8441502 , 0.45089745],
        [0.4500241 , 0.88523163, 0.79751223, 0.29819482, 0.47130553],
        [0.64987282, 0.36408489, 0.61829989, 0.74320921, 0.14845588],
        [0.59399

#operations in array

**copy**

**sort**

**reshape**

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
ar2=np.array([1,2,3,4,5,],dtype=np.int64)
ar2

array([1, 2, 3, 4, 5])

In [7]:
ar3=np.copy(ar2)
ar3

array([1, 2, 3, 4, 5])

In [10]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr=np.append(arr,4)
arr

array([1, 2, 3, 4, 5, 5, 4])

In [13]:
arr=np.append(arr,4)
arr

array([1, 2, 3, 4, 5, 5, 4, 4])

In [ ]:
concatination
#scalar expresson
add
subtract
multiply
divide
power


#stACtics
np.
